#!/bin/sh

# init_lcd
cat /proc/ls
sleep 2


# Waiting background
cd /mnt/SDCARD/.tmp_update/.ressources
./installUI &
sleep 2

#cd /mnt/SDCARD/.tmp_update/.data
#unzip ./data
#rm ./data

touch /mnt/SDCARD/.tmp_update/.ressources/.unpacked

# This is a new Onion installation (No BIOS folder yet)
mkdir /mnt/SDCARD/BIOS

cd /mnt/SDCARD/RetroArch/.retroarch
for FILE in ./system/*  
	# Transfering BIOS files		
	do
	mv -R $FILE /mnt/SDCARD/BIOS/
done

# Old Rom folder removal
cd /mnt/SDCARD
rm -rf RRoms


if [ -d /mnt/SDCARD/RetroArch/.retroarch/saves ] ; then
	mkdir /mnt/SDCARD/Backup
	mkdir /mnt/SDCARD/Backup/saves
	cd /mnt/SDCARD/RetroArch/.retroarch
	for FILE in ./saves/*  
		# Backup saves just in case someone did not read the README		
		do
		cp -R $FILE /mnt/SDCARD/Backup/saves/
	done
fi	

if [ -d /mnt/SDCARD/RetroArch/.retroarch/states ] ; then
	mkdir /mnt/SDCARD/Backup
	mkdir /mnt/SDCARD/Backup/states
	cd /mnt/SDCARD/RetroArch/.retroarch
	for FILE in ./states/*  
		# Backup states just in case someone did not read the README		
		do
		cp -R $FILE /mnt/SDCARD/Backup/states/
	done
fi

cd /mnt/SDCARD
rm -rf RetroArch

# Debloating the Apps
cd /mnt/SDCARD/App
rm -rf Commander_CN
rm -rf power
rm -rf RetroArch	

cd /mnt/SDCARD
rm -rf Emu
rm -rf RApp
rm -rf miyoo
	
mkdir Emu
mkdir RApp

# Onion Core installation / update
cd "/mnt/SDCARD/.tmp_update/.data"
for FILE in ./Core/*
	do
    cp -R "$FILE" "/mnt/SDCARD/"
done

touch /mnt/SDCARD/.tmp_update/.ressources/.coreInstalled
sleep 3

# Move layers 
cd "/mnt/SDCARD/.tmp_update/.data"
mv Layer1 "/mnt/SDCARD/App/The_Onion_Installer/data"
mv Layer2 "/mnt/SDCARD/App/The_Onion_Installer/data"
mv Layer3 "/mnt/SDCARD/App/The_Onion_Installer/data"

cd /mnt/SDCARD/App/Onion_Manual/
./launch.sh

cd /mnt/SDCARD/App/Onion_Manual/
./importantInfoPanel

sleep 1

cd /mnt/SDCARD/App/The_Onion_Installer/ 
./freemma

# Launch layer manager
cd /mnt/SDCARD/App/The_Onion_Installer/ 
./onionInstaller

cd /mnt/SDCARD/App/The_Onion_Installer/ 
./freemma

# force copy the updater for diplaying the manual

cd /mnt/SDCARD/
rm -rf .tmp_update

mkdir /mnt/SDCARD/.tmp_update
cp /mnt/SDCARD/App/Onion_Manual/updater /mnt/SDCARD/.tmp_update
chmod a+x /mnt/SDCARD/.tmp_update/updater
