#!/bin/sh

cat /proc/ls 
sleep 0.20
cd $(dirname "$0")
keymon &

if [ -f /mnt/SDCARD/App/Cartridge/data/.firstLaunch ] ; then
	rm /mnt/SDCARD/App/Cartridge/data/.firstLaunch
else
	cd /mnt/SDCARD/App/Cartridge/data/
	if [ ! -f ./.exit ] ; then
		cd /mnt/SDCARD/App/Cartridge/data/
		./checkEscape &
		sleep 0.25
		killall checkEscape
			
		if [ -f ./.exit ] ; then
			
			cd /mnt/SDCARD/
			rm -rf .tmp_update
			
			cd /mnt/SDCARD/App/Cartridge/data/
			./removed 
			reboot

		else
			cd /mnt/SDCARD/App/Cartridge/data/
			./autoClick.sh &
		fi
	fi
fi

touch /tmp/MainUI_exec && sync
while [ -f /tmp/MainUI_exec ]; do

cd /mnt/SDCARD/miyoo/app
./MainUI

if [ -f /tmp/.cmdenc ] ; then
    /root/gameloader
    elif [ -f /tmp/cmd_to_run.sh ] ; then
        chmod a+x /tmp/cmd_to_run.sh
        /tmp/cmd_to_run.sh
        rm /tmp/cmd_to_run.sh
fi


if [ -f /mnt/SDCARD/App/Cartridge/data/.firstLaunch ] ; then
	rm /mnt/SDCARD/App/Cartridge/data/.firstLaunch
else
	cd /mnt/SDCARD/App/Cartridge/data/
	if [ ! -f ./.exit ] ; then
		./turningOff &
		sleep 2
		killall turningOff

		if [ -f ./.exit ] ; then			
				cd /mnt/SDCARD/
				rm -rf .tmp_update
				
				cd /mnt/SDCARD/App/Cartridge/data/
				./removed 
		else
				reboot
		fi
	fi
fi











done



